config/routes.rb
Rails.application.routes.draw do
  resources :results

  resources :words

  get 'welcome/index'
  root 'welcome#index'
  
  post '/analyze' => 'welcome#analyze'

end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:hash, :eloquence_score, :high_register_word_ratio, :mean_word_count, :stddev, :sum_square_sentiment, :adjective_adverb_ratio, :linking_verb_ratio, :redundancy_factor)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hash %><br>
    <%= f.text_field :hash %>
  </div>
  <div class="field">
    <%= f.label :eloquence_score %><br>
    <%= f.text_field :eloquence_score %>
  </div>
  <div class="field">
    <%= f.label :high_register_word_ratio %><br>
    <%= f.text_field :high_register_word_ratio %>
  </div>
  <div class="field">
    <%= f.label :mean_word_count %><br>
    <%= f.text_field :mean_word_count %>
  </div>
  <div class="field">
    <%= f.label :stddev %><br>
    <%= f.text_field :stddev %>
  </div>
  <div class="field">
    <%= f.label :sum_square_sentiment %><br>
    <%= f.text_field :sum_square_sentiment %>
  </div>
  <div class="field">
    <%= f.label :adjective_adverb_ratio %><br>
    <%= f.text_field :adjective_adverb_ratio %>
  </div>
  <div class="field">
    <%= f.label :linking_verb_ratio %><br>
    <%= f.text_field :linking_verb_ratio %>
  </div>
  <div class="field">
    <%= f.label :redundancy_factor %><br>
    <%= f.text_field :redundancy_factor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <thead>
    <tr>
      <th>Hash</th>
      <th>Eloquence score</th>
      <th>High register word ratio</th>
      <th>Mean word count</th>
      <th>Stddev</th>
      <th>Sum square sentiment</th>
      <th>Adjective adverb ratio</th>
      <th>Linking verb ratio</th>
      <th>Redundancy factor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.hash %></td>
        <td><%= result.eloquence_score %></td>
        <td><%= result.high_register_word_ratio %></td>
        <td><%= result.mean_word_count %></td>
        <td><%= result.stddev %></td>
        <td><%= result.sum_square_sentiment %></td>
        <td><%= result.adjective_adverb_ratio %></td>
        <td><%= result.linking_verb_ratio %></td>
        <td><%= result.redundancy_factor %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hash:</strong>
  <%= @result.hash %>
</p>

<p>
  <strong>Eloquence score:</strong>
  <%= @result.eloquence_score %>
</p>

<p>
  <strong>High register word ratio:</strong>
  <%= @result.high_register_word_ratio %>
</p>

<p>
  <strong>Mean word count:</strong>
  <%= @result.mean_word_count %>
</p>

<p>
  <strong>Stddev:</strong>
  <%= @result.stddev %>
</p>

<p>
  <strong>Sum square sentiment:</strong>
  <%= @result.sum_square_sentiment %>
</p>

<p>
  <strong>Adjective adverb ratio:</strong>
  <%= @result.adjective_adverb_ratio %>
</p>

<p>
  <strong>Linking verb ratio:</strong>
  <%= @result.linking_verb_ratio %>
</p>

<p>
  <strong>Redundancy factor:</strong>
  <%= @result.redundancy_factor %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>