config/routes.rb
Rails.application.routes.draw do
  resources :results

  resources :words

  get 'welcome/index'
  root 'welcome#index'
  
  post '/analyze' => 'welcome#analyze'

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
	@word = Word.find(params[:id])
	syllables_count(@word.text)
	is_latinate(@word.text)
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:text, :is_latinate, :syllables_count, :part_of_speech, :is_linking_verb, :canonical)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :is_latinate %><br>
    <%= f.check_box :is_latinate %>
  </div>
  <div class="field">
    <%= f.label :syllables_count %><br>
    <%= f.number_field :syllables_count %>
  </div>
  <div class="field">
    <%= f.label :part_of_speech %><br>
    <%= f.text_field :part_of_speech %>
  </div>
  <div class="field">
    <%= f.label :is_linking_verb %><br>
    <%= f.check_box :is_linking_verb %>
  </div>
  <div class="field">
    <%= f.label :canonical %><br>
    <%= f.text_field :canonical %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Is latinate</th>
      <th>Syllables count</th>
      <th>Part of speech</th>
      <th>Is linking verb</th>
      <th>Canonical</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.text %></td>
        <td><%= word.is_latinate %></td>
        <td><%= word.syllables_count %></td>
        <td><%= word.part_of_speech %></td>
        <td><%= word.is_linking_verb %></td>
        <td><%= word.canonical %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @word.text %>
</p>

<p>
  <strong>Is latinate:</strong>
  <%= @word.is_latinate %>
</p>

<p>
  <strong>Syllables count:</strong>
  <%= @word.syllables_count %>
</p>

<p>
  <strong>Part of speech:</strong>
  <%= @word.part_of_speech %>
</p>

<p>
  <strong>Is linking verb:</strong>
  <%= @word.is_linking_verb %>
</p>

<p>
  <strong>Canonical:</strong>
  <%= @word.canonical %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>